version: "3"  # Versão da configuração do Docker Compose

services:
  app:  # Nome do serviço
    build: .  # Define o contexto para construir a imagem a partir do Dockerfile no diretório atual

    extra_hosts:  # Define mapeamento de hosts adicionais (neste caso, mapeia host.docker.internal para host-gateway)
      - "host.docker.internal:host-gateway"

    container_name: api  # Define o nome do contêiner como "api"

    ports:
      - "8099:80"  # Mapeia a porta 8099 do host para a porta 80 do contêiner

    volumes:
      - .:/var/www/html  # Mapeia o diretório atual (no host) para /var/www/html (no contêiner)

    command: >  # Define o comando a ser executado no contêiner
      sh -c "service apache2 start && redis-server --protected-mode no"
